"""create provenance registry

Revision ID: 20260729_0001
Revises:
Create Date: 2026-07-29 21:14:28.300746
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "20260729_0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

_OWNED_TABLES = {
    "alembic_version",
    "dataset_artifacts",
    "dataset_input_files",
    "dataset_sources",
    "dataset_versions",
    "quality_results",
    "source_snapshot_files",
    "source_snapshots",
}


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "dataset_versions",
        sa.Column("dataset_id", sa.String(length=255), nullable=False),
        sa.Column("dataset_version", sa.String(length=100), nullable=False),
        sa.Column("schema_version", sa.Integer(), nullable=False),
        sa.Column("row_count", sa.BigInteger(), nullable=False),
        sa.Column("coverage_start", sa.Date(), nullable=True),
        sa.Column("coverage_end", sa.Date(), nullable=True),
        sa.Column("identity_coverage", sa.Numeric(precision=6, scale=5), nullable=False),
        sa.Column("freshness_status", sa.String(length=16), nullable=False),
        sa.Column("transformation_version", sa.String(length=100), nullable=False),
        sa.Column("aggregate_content_sha256", sa.String(length=64), nullable=False),
        sa.Column("canonical_eligible", sa.Boolean(), nullable=False),
        sa.Column("backtest_eligible", sa.Boolean(), nullable=False),
        sa.Column("paper_eligible", sa.Boolean(), nullable=False),
        sa.Column("order_eligible", sa.Boolean(), nullable=False),
        sa.Column("created_at_utc", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "freshness_status IN ('PASS', 'WARN', 'BLOCKED')",
            name=op.f("ck_dataset_versions_freshness_status_allowed"),
        ),
        sa.CheckConstraint(
            "length(aggregate_content_sha256) = 64 AND aggregate_content_sha256 ~ '^[0-9a-f]{64}$'",
            name=op.f("ck_dataset_versions_aggregate_content_sha256_sha256"),
        ),
        sa.CheckConstraint(
            "NOT canonical_eligible AND NOT backtest_eligible "
            "AND NOT paper_eligible AND NOT order_eligible",
            name=op.f("ck_dataset_versions_eligibility_blocked_in_v1"),
        ),
        sa.CheckConstraint(
            "coverage_start IS NULL OR coverage_end IS NULL OR coverage_end >= coverage_start",
            name=op.f("ck_dataset_versions_coverage_order"),
        ),
        sa.CheckConstraint(
            "identity_coverage >= 0 AND identity_coverage <= 1",
            name=op.f("ck_dataset_versions_identity_coverage_range"),
        ),
        sa.CheckConstraint(
            "row_count >= 0", name=op.f("ck_dataset_versions_row_count_nonnegative")
        ),
        sa.CheckConstraint(
            "schema_version > 0", name=op.f("ck_dataset_versions_schema_version_positive")
        ),
        sa.CheckConstraint(
            "btrim(dataset_id) <> ''",
            name=op.f("ck_dataset_versions_dataset_id_nonempty"),
        ),
        sa.CheckConstraint(
            "btrim(dataset_version) <> ''",
            name=op.f("ck_dataset_versions_dataset_version_nonempty"),
        ),
        sa.CheckConstraint(
            "btrim(transformation_version) <> ''",
            name=op.f("ck_dataset_versions_transformation_version_nonempty"),
        ),
        sa.PrimaryKeyConstraint("dataset_id", "dataset_version", name=op.f("pk_dataset_versions")),
    )
    op.create_table(
        "source_snapshots",
        sa.Column("snapshot_id", sa.String(length=255), nullable=False),
        sa.Column("schema_version", sa.Integer(), nullable=False),
        sa.Column("provider", sa.String(length=100), nullable=False),
        sa.Column("dataset", sa.String(length=150), nullable=False),
        sa.Column("source_uri", sa.Text(), nullable=False),
        sa.Column("request_fingerprint", sa.String(length=71), nullable=False),
        sa.Column(
            "parameters_json",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("requested_at_utc", sa.DateTime(timezone=True), nullable=False),
        sa.Column("retrieved_at_utc", sa.DateTime(timezone=True), nullable=False),
        sa.Column("provider_published_at_utc", sa.DateTime(timezone=True), nullable=True),
        sa.Column("provider_watermark", sa.Text(), nullable=True),
        sa.Column("observation_date", sa.String(length=32), nullable=True),
        sa.Column("content_type", sa.String(length=150), nullable=False),
        sa.Column("encoding", sa.String(length=100), nullable=True),
        sa.Column("compression", sa.String(length=100), nullable=True),
        sa.Column("raw_byte_length", sa.BigInteger(), nullable=False),
        sa.Column("content_sha256", sa.String(length=64), nullable=False),
        sa.Column("tree_sha256", sa.String(length=64), nullable=True),
        sa.Column("parser_name", sa.String(length=150), nullable=False),
        sa.Column("parser_version", sa.String(length=100), nullable=False),
        sa.Column("validation_status", sa.String(length=16), nullable=False),
        sa.Column("row_count", sa.BigInteger(), nullable=True),
        sa.Column("coverage_start", sa.Date(), nullable=True),
        sa.Column("coverage_end", sa.Date(), nullable=True),
        sa.Column("license_classification", sa.String(length=100), nullable=False),
        sa.Column("retention_classification", sa.String(length=100), nullable=False),
        sa.Column(
            "manifest_json",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "registered_at_utc",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "length(content_sha256) = 64 AND content_sha256 ~ '^[0-9a-f]{64}$'",
            name=op.f("ck_source_snapshots_content_sha256_sha256"),
        ),
        sa.CheckConstraint(
            "request_fingerprint ~ '^sha256:[0-9a-f]{64}$'",
            name=op.f("ck_source_snapshots_request_fingerprint_sha256"),
        ),
        sa.CheckConstraint(
            "tree_sha256 IS NULL OR (length(tree_sha256) = 64 AND tree_sha256 ~ '^[0-9a-f]{64}$')",
            name=op.f("ck_source_snapshots_tree_sha256"),
        ),
        sa.CheckConstraint(
            "validation_status IN ('PASS', 'WARN', 'BLOCKED')",
            name=op.f("ck_source_snapshots_validation_status_allowed"),
        ),
        sa.CheckConstraint(
            "coverage_start IS NULL OR coverage_end IS NULL OR coverage_end >= coverage_start",
            name=op.f("ck_source_snapshots_coverage_order"),
        ),
        sa.CheckConstraint(
            "raw_byte_length >= 0", name=op.f("ck_source_snapshots_raw_byte_length_nonnegative")
        ),
        sa.CheckConstraint(
            "retrieved_at_utc >= requested_at_utc",
            name=op.f("ck_source_snapshots_request_retrieval_order"),
        ),
        sa.CheckConstraint(
            "row_count IS NULL OR row_count >= 0",
            name=op.f("ck_source_snapshots_row_count_nonnegative"),
        ),
        sa.CheckConstraint(
            "schema_version > 0", name=op.f("ck_source_snapshots_schema_version_positive")
        ),
        sa.CheckConstraint(
            "btrim(snapshot_id) <> ''",
            name=op.f("ck_source_snapshots_snapshot_id_nonempty"),
        ),
        sa.CheckConstraint(
            "btrim(provider) <> ''",
            name=op.f("ck_source_snapshots_provider_nonempty"),
        ),
        sa.CheckConstraint(
            "btrim(dataset) <> ''",
            name=op.f("ck_source_snapshots_dataset_nonempty"),
        ),
        sa.CheckConstraint(
            "btrim(source_uri) <> ''",
            name=op.f("ck_source_snapshots_source_uri_nonempty"),
        ),
        sa.CheckConstraint(
            "btrim(content_type) <> ''",
            name=op.f("ck_source_snapshots_content_type_nonempty"),
        ),
        sa.CheckConstraint(
            "btrim(parser_name) <> ''",
            name=op.f("ck_source_snapshots_parser_name_nonempty"),
        ),
        sa.CheckConstraint(
            "btrim(parser_version) <> ''",
            name=op.f("ck_source_snapshots_parser_version_nonempty"),
        ),
        sa.CheckConstraint(
            "btrim(license_classification) <> ''",
            name=op.f("ck_source_snapshots_license_classification_nonempty"),
        ),
        sa.CheckConstraint(
            "btrim(retention_classification) <> ''",
            name=op.f("ck_source_snapshots_retention_classification_nonempty"),
        ),
        sa.PrimaryKeyConstraint("snapshot_id", name=op.f("pk_source_snapshots")),
    )
    op.create_index(
        op.f("ix_source_snapshots_provider"), "source_snapshots", ["provider"], unique=False
    )
    op.create_table(
        "dataset_artifacts",
        sa.Column("dataset_id", sa.String(length=255), nullable=False),
        sa.Column("dataset_version", sa.String(length=100), nullable=False),
        sa.Column("relative_path", sa.Text(), nullable=False),
        sa.Column("media_type", sa.String(length=150), nullable=False),
        sa.Column("size_bytes", sa.BigInteger(), nullable=False),
        sa.Column("row_count", sa.BigInteger(), nullable=True),
        sa.Column("content_sha256", sa.String(length=64), nullable=False),
        sa.Column(
            "partition_values_json",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "length(content_sha256) = 64 AND content_sha256 ~ '^[0-9a-f]{64}$'",
            name=op.f("ck_dataset_artifacts_content_sha256_sha256"),
        ),
        sa.CheckConstraint(
            "relative_path !~ '(^/|(^|/)\\.\\.(/|$))'",
            name=op.f("ck_dataset_artifacts_relative_path_safe"),
        ),
        sa.CheckConstraint(
            "btrim(relative_path) <> ''",
            name=op.f("ck_dataset_artifacts_relative_path_nonempty"),
        ),
        sa.CheckConstraint(
            "btrim(media_type) <> ''",
            name=op.f("ck_dataset_artifacts_media_type_nonempty"),
        ),
        sa.CheckConstraint(
            "row_count IS NULL OR row_count >= 0",
            name=op.f("ck_dataset_artifacts_row_count_nonnegative"),
        ),
        sa.CheckConstraint(
            "size_bytes >= 0", name=op.f("ck_dataset_artifacts_size_bytes_nonnegative")
        ),
        sa.ForeignKeyConstraint(
            ["dataset_id", "dataset_version"],
            ["dataset_versions.dataset_id", "dataset_versions.dataset_version"],
            name=op.f("fk_dataset_artifacts_dataset_id_dataset_versions"),
            match="FULL",
        ),
        sa.PrimaryKeyConstraint(
            "dataset_id", "dataset_version", "relative_path", name=op.f("pk_dataset_artifacts")
        ),
    )
    op.create_table(
        "dataset_sources",
        sa.Column("dataset_id", sa.String(length=255), nullable=False),
        sa.Column("dataset_version", sa.String(length=100), nullable=False),
        sa.Column("source_snapshot_id", sa.String(length=255), nullable=False),
        sa.ForeignKeyConstraint(
            ["dataset_id", "dataset_version"],
            ["dataset_versions.dataset_id", "dataset_versions.dataset_version"],
            name=op.f("fk_dataset_sources_dataset_id_dataset_versions"),
            match="FULL",
        ),
        sa.ForeignKeyConstraint(
            ["source_snapshot_id"],
            ["source_snapshots.snapshot_id"],
            name=op.f("fk_dataset_sources_source_snapshot_id_source_snapshots"),
        ),
        sa.PrimaryKeyConstraint(
            "dataset_id", "dataset_version", "source_snapshot_id", name=op.f("pk_dataset_sources")
        ),
    )
    op.create_table(
        "quality_results",
        sa.Column("result_id", sa.String(length=255), nullable=False),
        sa.Column("check_id", sa.String(length=255), nullable=False),
        sa.Column("check_version", sa.String(length=100), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column(
            "dimensions_json",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "details_json",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("safe_next_action", sa.Text(), nullable=False),
        sa.Column("checked_at_utc", sa.DateTime(timezone=True), nullable=False),
        sa.Column("source_snapshot_id", sa.String(length=255), nullable=True),
        sa.Column("dataset_id", sa.String(length=255), nullable=True),
        sa.Column("dataset_version", sa.String(length=100), nullable=True),
        sa.CheckConstraint(
            "status IN ('PASS', 'WARN', 'BLOCKED')", name=op.f("ck_quality_results_status_allowed")
        ),
        sa.CheckConstraint(
            "btrim(result_id) <> ''",
            name=op.f("ck_quality_results_result_id_nonempty"),
        ),
        sa.CheckConstraint(
            "btrim(check_id) <> ''",
            name=op.f("ck_quality_results_check_id_nonempty"),
        ),
        sa.CheckConstraint(
            "btrim(check_version) <> ''",
            name=op.f("ck_quality_results_check_version_nonempty"),
        ),
        sa.CheckConstraint(
            "btrim(safe_next_action) <> ''",
            name=op.f("ck_quality_results_safe_next_action_nonempty"),
        ),
        sa.CheckConstraint(
            "(source_snapshot_id IS NOT NULL AND dataset_id IS NULL "
            "AND dataset_version IS NULL) OR (source_snapshot_id IS NULL "
            "AND dataset_id IS NOT NULL AND dataset_version IS NOT NULL)",
            name=op.f("ck_quality_results_exactly_one_subject"),
        ),
        sa.ForeignKeyConstraint(
            ["dataset_id", "dataset_version"],
            ["dataset_versions.dataset_id", "dataset_versions.dataset_version"],
            name=op.f("fk_quality_results_dataset_id_dataset_versions"),
            match="FULL",
        ),
        sa.ForeignKeyConstraint(
            ["source_snapshot_id"],
            ["source_snapshots.snapshot_id"],
            name=op.f("fk_quality_results_source_snapshot_id_source_snapshots"),
        ),
        sa.PrimaryKeyConstraint("result_id", name=op.f("pk_quality_results")),
        sa.UniqueConstraint(
            "dataset_id", "dataset_version", "result_id", name="dataset_quality_result"
        ),
    )
    op.create_table(
        "source_snapshot_files",
        sa.Column("snapshot_id", sa.String(length=255), nullable=False),
        sa.Column("relative_path", sa.Text(), nullable=False),
        sa.Column("size_bytes", sa.BigInteger(), nullable=False),
        sa.Column("content_sha256", sa.String(length=64), nullable=False),
        sa.CheckConstraint(
            "length(content_sha256) = 64 AND content_sha256 ~ '^[0-9a-f]{64}$'",
            name=op.f("ck_source_snapshot_files_content_sha256_sha256"),
        ),
        sa.CheckConstraint(
            "relative_path !~ '(^/|(^|/)\\.\\.(/|$))'",
            name=op.f("ck_source_snapshot_files_relative_path_safe"),
        ),
        sa.CheckConstraint(
            "btrim(relative_path) <> ''",
            name=op.f("ck_source_snapshot_files_relative_path_nonempty"),
        ),
        sa.CheckConstraint(
            "size_bytes >= 0", name=op.f("ck_source_snapshot_files_size_bytes_nonnegative")
        ),
        sa.ForeignKeyConstraint(
            ["snapshot_id"],
            ["source_snapshots.snapshot_id"],
            name=op.f("fk_source_snapshot_files_snapshot_id_source_snapshots"),
        ),
        sa.PrimaryKeyConstraint(
            "snapshot_id", "relative_path", name=op.f("pk_source_snapshot_files")
        ),
    )
    op.create_table(
        "dataset_input_files",
        sa.Column("dataset_id", sa.String(length=255), nullable=False),
        sa.Column("dataset_version", sa.String(length=100), nullable=False),
        sa.Column("source_snapshot_id", sa.String(length=255), nullable=False),
        sa.Column("relative_path", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["dataset_id", "dataset_version", "source_snapshot_id"],
            [
                "dataset_sources.dataset_id",
                "dataset_sources.dataset_version",
                "dataset_sources.source_snapshot_id",
            ],
            name=op.f("fk_dataset_input_files_dataset_id_dataset_sources"),
            match="FULL",
        ),
        sa.CheckConstraint(
            "btrim(relative_path) <> ''",
            name=op.f("ck_dataset_input_files_relative_path_nonempty"),
        ),
        sa.ForeignKeyConstraint(
            ["source_snapshot_id", "relative_path"],
            ["source_snapshot_files.snapshot_id", "source_snapshot_files.relative_path"],
            name=op.f("fk_dataset_input_files_source_snapshot_id_source_snapshot_files"),
            match="FULL",
        ),
        sa.PrimaryKeyConstraint(
            "dataset_id",
            "dataset_version",
            "source_snapshot_id",
            "relative_path",
            name=op.f("pk_dataset_input_files"),
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    _assert_fixture_owned_database()
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("dataset_input_files")
    op.drop_table("source_snapshot_files")
    op.drop_table("quality_results")
    op.drop_table("dataset_sources")
    op.drop_table("dataset_artifacts")
    op.drop_index(op.f("ix_source_snapshots_provider"), table_name="source_snapshots")
    op.drop_table("source_snapshots")
    op.drop_table("dataset_versions")
    # ### end Alembic commands ###


def _assert_fixture_owned_database() -> None:
    """Fail closed: destructive downgrade is test-fixture-only in schema v1."""

    context = op.get_context()
    expected_name = context.config.attributes.get("aas_test_database_name")
    expected_token = context.config.attributes.get("aas_test_owner_token")
    connection = op.get_bind()
    current_name = connection.scalar(sa.text("SELECT current_database()"))
    observed_token = connection.scalar(
        sa.text(
            "SELECT shobj_description(oid, 'pg_database') "
            "FROM pg_database WHERE datname = current_database()"
        )
    )
    observed_tables = set(sa.inspect(connection).get_table_names())
    if (
        not isinstance(expected_name, str)
        or not isinstance(expected_token, str)
        or current_name != expected_name
        or observed_token != expected_token
        or not expected_name.startswith("aas_owned_")
        or not expected_name.endswith("_test")
        or not observed_tables <= _OWNED_TABLES
    ):
        raise RuntimeError("refusing destructive downgrade outside an owned empty test database")
